name: Compile Android binaries

on:
  push:
    branches: [ master, project-upgrade ]
  pull_request:
    branches: [ master ]
  release:
     types: 
       - published
       - prereleased
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.101
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install .NET Android workload
      run: dotnet workload install android
  
    - name: Restore dependencies
      run: dotnet restore --configfile GalaxyBudsClient/nuget.config GalaxyBudsClient.Android/GalaxyBudsClient.Android.csproj
      
    - name: Build Generators project
      run: dotnet build GalaxyBudsClient.Generators/GalaxyBudsClient.Generators.csproj -c Release
      
    - name: Build APK
      run: |
        dotnet clean
        dotnet publish -f net8.0-android -c Release \
          -p:AndroidPackageFormats=apk \
          -p:AndroidKeyStore=false \
          -p:DebugType=PdbOnly \
          -p:NotDebuggable=true \
          -p:EmbedAssembliesIntoApk=true \
          -p:RuntimeIdentifier=android-arm64 \
          -p:AndroidSupportedAbis=arm64-v8a \
          GalaxyBudsClient.Android/GalaxyBudsClient.Android.csproj

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: GalaxyBudsClient_Android_APK
        path: GalaxyBudsClient.Android/bin/Release/net8.0-android/*.apk
